spring:
    http:
        encoding:
            charset: UTF-8
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        # static-path-pattern: /static/**
    output:
        ansi:
            enabled: always
    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
    resources:
        static-locations: classpath:/static/
        add-mappings: true
        
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.50.172.150:3306/mydb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        
server:
    servlet:
        context-path: /
        session: 
            timeout: 14400
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    
mybatis:
    mapper-locations: classpath:Mappers/*Mapper.xml

cloud:
    aws:
        credentials:
            accessKey: U2bC5kMpLkfMflV4TokB
            secretKey: Q7UD9L7sN2vsanfZoMU7RAkpIZlRTARVvzs0EPIh
